# Generated by Django 4.2.5 on 2023-09-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extracurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('field', models.IntegerField(null=True)),
                ('type', models.IntegerField(null=True)),
                ('mode', models.IntegerField(null=True)),
                ('season', models.IntegerField(null=True)),
                ('selectivity', models.IntegerField(null=True)),
                ('cost', models.IntegerField(null=True)),
            ],
        ),
    ]
