# Generated by Django 4.2.5 on 2023-09-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldExtracurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('field', models.IntegerField(null=True)),
                ('type', models.IntegerField(null=True)),
                ('mode', models.IntegerField(null=True)),
                ('season', models.IntegerField(null=True)),
                ('selectivity', models.IntegerField(null=True)),
                ('cost', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='cost',
            field=models.IntegerField(choices=[(1, 'Free Summer Program'), (2, 'Paid Summer Program'), (3, 'Unpaid Internship'), (4, 'Paid Internship')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='field',
            field=models.IntegerField(choices=[(1, 'Computer Science'), (2, 'Engineering'), (3, 'Mathematics'), (4, 'Science'), (5, 'Medicine'), (6, 'Business'), (7, 'Law'), (8, 'Politics'), (9, 'History'), (10, 'Arts'), (11, 'Writing'), (12, 'Psychology'), (13, 'Environment'), (14, 'Architecture')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='mode',
            field=models.IntegerField(choices=[(1, 'Remote'), (2, 'In-Person'), (3, 'Hybrid')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='season',
            field=models.IntegerField(choices=[(1, 'Summer'), (2, 'School Year')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='selectivity',
            field=models.IntegerField(choices=[(1, 'Less Selective'), (2, 'Medium Selective'), (3, 'Very'), (4, 'Selective')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='type',
            field=models.IntegerField(choices=[(1, 'Internship'), (2, 'Research'), (3, 'Program')], default=None, null=True),
        ),
    ]
