# Generated by Django 4.2.5 on 2023-09-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='tags',
            field=models.ManyToManyField(default={}, to='users.tag'),
        ),
    ]
