# Generated by Django 4.2.5 on 2023-09-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_extracurricular_grade_extracurricular_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwardReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("website", models.URLField(blank=True)),
                (
                    "field",
                    models.IntegerField(
                        choices=[
                            (1, "Computer Science"),
                            (2, "Engineering"),
                            (3, "Mathematics"),
                            (4, "Science"),
                            (5, "Medicine"),
                            (6, "Business"),
                            (7, "Law"),
                            (8, "Politics"),
                            (9, "History"),
                            (10, "Arts"),
                            (11, "Writing"),
                            (12, "Psychology"),
                            (13, "Environment"),
                            (14, "Architecture"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Internship"), (2, "Research"), (3, "Program")],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "mode",
                    models.IntegerField(
                        choices=[(1, "Remote"), (2, "In-Person"), (3, "Hybrid")],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "season",
                    models.IntegerField(
                        choices=[(1, "Summer"), (2, "School Year")],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "selectivity",
                    models.IntegerField(
                        choices=[
                            (1, "Less Selective"),
                            (2, "Medium Selective"),
                            (3, "Very Selective"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "cost",
                    models.IntegerField(
                        choices=[
                            (1, "Free Summer Program"),
                            (2, "Paid Summer Program"),
                            (3, "Unpaid Internship"),
                            (4, "Paid Internship"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "Grade",
                    models.IntegerField(
                        choices=[
                            (1, "9"),
                            (2, "10"),
                            (3, "11"),
                            (4, "12"),
                            (5, "All Grades"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "Location",
                    models.IntegerField(
                        choices=[(1, "Usa"), (2, "Global")], default=None, null=True
                    ),
                ),
                (
                    "Offered_By",
                    models.IntegerField(
                        choices=[
                            (1, "Educational Insitution"),
                            (2, "Nonprofit Organization"),
                            (3, "Business Corporation"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "Organization",
                    models.IntegerField(
                        choices=[(1, "Club"), (2, "Program")], default=None, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtracurricularReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("website", models.URLField(blank=True)),
                (
                    "field",
                    models.IntegerField(
                        choices=[
                            (1, "Computer Science"),
                            (2, "Engineering"),
                            (3, "Mathematics"),
                            (4, "Science"),
                            (5, "Medicine"),
                            (6, "Business"),
                            (7, "Law"),
                            (8, "Politics"),
                            (9, "History"),
                            (10, "Arts"),
                            (11, "Writing"),
                            (12, "Psychology"),
                            (13, "Environment"),
                            (14, "Architecture"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Internship"), (2, "Research"), (3, "Program")],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "mode",
                    models.IntegerField(
                        choices=[(1, "Remote"), (2, "In-Person"), (3, "Hybrid")],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "season",
                    models.IntegerField(
                        choices=[(1, "Summer"), (2, "School Year")],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "selectivity",
                    models.IntegerField(
                        choices=[
                            (1, "Less Selective"),
                            (2, "Medium Selective"),
                            (3, "Very Selective"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "cost",
                    models.IntegerField(
                        choices=[
                            (1, "Free Summer Program"),
                            (2, "Paid Summer Program"),
                            (3, "Unpaid Internship"),
                            (4, "Paid Internship"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "Grade",
                    models.IntegerField(
                        choices=[
                            (1, "9"),
                            (2, "10"),
                            (3, "11"),
                            (4, "12"),
                            (5, "All Grades"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "Location",
                    models.IntegerField(
                        choices=[(1, "Usa"), (2, "Global")], default=None, null=True
                    ),
                ),
                (
                    "Offered_By",
                    models.IntegerField(
                        choices=[
                            (1, "Educational Insitution"),
                            (2, "Nonprofit Organization"),
                            (3, "Business Corporation"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "Organization",
                    models.IntegerField(
                        choices=[(1, "Club"), (2, "Program")], default=None, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScholarshipReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("website", models.URLField(blank=True)),
                (
                    "field",
                    models.IntegerField(
                        choices=[
                            (1, "Computer Science"),
                            (2, "Engineering"),
                            (3, "Mathematics"),
                            (4, "Science"),
                            (5, "Medicine"),
                            (6, "Business"),
                            (7, "Law"),
                            (8, "Politics"),
                            (9, "History"),
                            (10, "Arts"),
                            (11, "Writing"),
                            (12, "Psychology"),
                            (13, "Environment"),
                            (14, "Architecture"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "Internship"), (2, "Research"), (3, "Program")],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "mode",
                    models.IntegerField(
                        choices=[(1, "Remote"), (2, "In-Person"), (3, "Hybrid")],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "season",
                    models.IntegerField(
                        choices=[(1, "Summer"), (2, "School Year")],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "selectivity",
                    models.IntegerField(
                        choices=[
                            (1, "Less Selective"),
                            (2, "Medium Selective"),
                            (3, "Very Selective"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "cost",
                    models.IntegerField(
                        choices=[
                            (1, "Free Summer Program"),
                            (2, "Paid Summer Program"),
                            (3, "Unpaid Internship"),
                            (4, "Paid Internship"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "Grade",
                    models.IntegerField(
                        choices=[
                            (1, "9"),
                            (2, "10"),
                            (3, "11"),
                            (4, "12"),
                            (5, "All Grades"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "Location",
                    models.IntegerField(
                        choices=[(1, "Usa"), (2, "Global")], default=None, null=True
                    ),
                ),
                (
                    "Offered_By",
                    models.IntegerField(
                        choices=[
                            (1, "Educational Insitution"),
                            (2, "Nonprofit Organization"),
                            (3, "Business Corporation"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "Organization",
                    models.IntegerField(
                        choices=[(1, "Club"), (2, "Program")], default=None, null=True
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Extracurricular",
        ),
    ]
