# Generated by Django 4.2.5 on 2023-09-23 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_awardreference_category_extracurricularreference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Grade',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Offered_By',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Organization',
        ),
        migrations.RemoveField(
            model_name='category',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='category',
            name='field',
        ),
        migrations.RemoveField(
            model_name='category',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='category',
            name='season',
        ),
        migrations.RemoveField(
            model_name='category',
            name='selectivity',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AddField(
            model_name='awardreference',
            name='cost',
            field=models.IntegerField(choices=[(1, 'Free Summer Program'), (2, 'Paid Summer Program'), (3, 'Unpaid Internship'), (4, 'Paid Internship')], null=True),
        ),
        migrations.AddField(
            model_name='awardreference',
            name='field',
            field=models.IntegerField(choices=[(1, 'Computer Science'), (2, 'Engineering')], null=True),
        ),
        migrations.AddField(
            model_name='awardreference',
            name='mode',
            field=models.IntegerField(choices=[(1, 'Remote'), (2, 'In-person'), (3, 'Hybrid')], null=True),
        ),
        migrations.AddField(
            model_name='awardreference',
            name='season',
            field=models.IntegerField(choices=[(1, 'Summer'), (2, 'School Year')], null=True),
        ),
        migrations.AddField(
            model_name='awardreference',
            name='selectivity',
            field=models.IntegerField(choices=[(1, 'Less Selective'), (2, 'Medium Selective'), (3, 'Very Selective')], null=True),
        ),
        migrations.AddField(
            model_name='awardreference',
            name='type',
            field=models.IntegerField(choices=[(1, 'Internship'), (2, 'Research')], null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extracurricularreference',
            name='cost',
            field=models.IntegerField(choices=[(1, 'Free Summer Program'), (2, 'Paid Summer Program'), (3, 'Unpaid Internship'), (4, 'Paid Internship')], null=True),
        ),
        migrations.AddField(
            model_name='extracurricularreference',
            name='field',
            field=models.IntegerField(choices=[(1, 'Computer Science'), (2, 'Engineering')], null=True),
        ),
        migrations.AddField(
            model_name='extracurricularreference',
            name='mode',
            field=models.IntegerField(choices=[(1, 'Remote'), (2, 'In-person'), (3, 'Hybrid')], null=True),
        ),
        migrations.AddField(
            model_name='extracurricularreference',
            name='season',
            field=models.IntegerField(choices=[(1, 'Summer'), (2, 'School Year')], null=True),
        ),
        migrations.AddField(
            model_name='extracurricularreference',
            name='selectivity',
            field=models.IntegerField(choices=[(1, 'Less Selective'), (2, 'Medium Selective'), (3, 'Very Selective')], null=True),
        ),
        migrations.AddField(
            model_name='extracurricularreference',
            name='type',
            field=models.IntegerField(choices=[(1, 'Internship'), (2, 'Research')], null=True),
        ),
        migrations.AddField(
            model_name='scholarshipreference',
            name='cost',
            field=models.IntegerField(choices=[(1, 'Free Summer Program'), (2, 'Paid Summer Program'), (3, 'Unpaid Internship'), (4, 'Paid Internship')], null=True),
        ),
        migrations.AddField(
            model_name='scholarshipreference',
            name='field',
            field=models.IntegerField(choices=[(1, 'Computer Science'), (2, 'Engineering')], null=True),
        ),
        migrations.AddField(
            model_name='scholarshipreference',
            name='mode',
            field=models.IntegerField(choices=[(1, 'Remote'), (2, 'In-person'), (3, 'Hybrid')], null=True),
        ),
        migrations.AddField(
            model_name='scholarshipreference',
            name='season',
            field=models.IntegerField(choices=[(1, 'Summer'), (2, 'School Year')], null=True),
        ),
        migrations.AddField(
            model_name='scholarshipreference',
            name='selectivity',
            field=models.IntegerField(choices=[(1, 'Less Selective'), (2, 'Medium Selective'), (3, 'Very Selective')], null=True),
        ),
        migrations.AddField(
            model_name='scholarshipreference',
            name='type',
            field=models.IntegerField(choices=[(1, 'Internship'), (2, 'Research')], null=True),
        ),
        migrations.AlterField(
            model_name='awardreference',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.category'),
        ),
        migrations.AlterField(
            model_name='extracurricularreference',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.category'),
        ),
        migrations.AlterField(
            model_name='scholarshipreference',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.category'),
        ),
    ]

