# Generated by Django 4.2.5 on 2023-09-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_awardreference_extracurricularreference_and_more'),
        ('users', '0006_awardreference_grade_awardreference_location_and_more'),
    ]

    operations = [
    ]
