# Generated by Django 4.2.5 on 2023-09-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_awardreference_grade_awardreference_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardreference',
            name='grade',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='awardreference',
            name='offered_by',
            field=models.IntegerField(choices=[(1, 'Educational Institution'), (2, 'Non-profit Organization'), (3, 'Business Corporation')], null=True),
        ),
        migrations.AlterField(
            model_name='extracurricularreference',
            name='grade',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='extracurricularreference',
            name='offered_by',
            field=models.IntegerField(choices=[(1, 'Educational Institution'), (2, 'Non-profit Organization'), (3, 'Business Corporation')], null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipreference',
            name='grade',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipreference',
            name='offered_by',
            field=models.IntegerField(choices=[(1, 'Educational Institution'), (2, 'Non-profit Organization'), (3, 'Business Corporation')], null=True),
        ),
    ]
