# Generated by Django 4.2.5 on 2023-09-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_opportunity_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracurricularreference',
            name='category',
        ),
        migrations.RemoveField(
            model_name='scholarshipreference',
            name='category',
        ),
        migrations.DeleteModel(
            name='AwardReference',
        ),
        migrations.DeleteModel(
            name='ExtracurricularReference',
        ),
        migrations.DeleteModel(
            name='ScholarshipReference',
        ),
    ]
