# Generated by Django 4.2.5 on 2023-09-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_waitlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='tags',
            field=models.ManyToManyField(blank=True, to='users.tag'),
        ),
    ]
